In [1]:
!curl -LsSf https://astral.sh/uv/install.sh | sh

downloading uv 0.11.1 x86_64-unknown-linux-gnu
installing to /home/codespace/.local/bin
  uv
  uvx
everything's installed!

In [2]:
!uv self update

info: Checking for updates...
success: You're already on version v0.11.1 of uv (the latest version).

# Creating virtual enviroment
    1  uv venv venv
    2  source venv/bin/activate
    3  uv pip install ipykernel
    4  python -m ipykernel install --user --name=venv
    5  history

In [2]:
!uv pip install numpy

Using Python 3.12.1 environment at: venv
Checked 1 package in 1ms

In [3]:
!uv pip install pandas

Using Python 3.12.1 environment at: venv
Checked 1 package in 10ms

In [4]:
import numpy as np
import pandas as pd

In [7]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [8]:
date = pd.date_range("20260102",periods=6)
date

DatetimeIndex(['2026-01-02', '2026-01-03', '2026-01-04', '2026-01-05',
               '2026-01-06', '2026-01-07'],
              dtype='datetime64[us]', freq='D')

In [11]:
df = pd.DataFrame(np.random.randn(6,4), index=date, columns=list("ABCD"))
df

                   A         B         C         D
2026-01-02 -0.929508  0.794743  1.079821  1.115524
2026-01-03 -1.407306 -2.013805  0.329798  1.727386
2026-01-04 -1.148989  1.152806  0.369733 -0.013631
2026-01-05 -0.090984  0.617422  0.620825 -0.872470
2026-01-06  1.407513  0.521418 -1.991583  0.404384
2026-01-07 -0.540120  0.276446  0.065943 -0.536695

In [13]:
df2 =pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20260326"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3]*4, dtype="int32"),
        "E" : pd.Categorical(["test","train", "test", "train"]),
        "F" : "foo"

    }
)

df2

     A          B    C  D      E    F
0  1.0 2026-03-26  1.0  3   test  foo
1  1.0 2026-03-26  1.0  3  train  foo
2  1.0 2026-03-26  1.0  3   test  foo
3  1.0 2026-03-26  1.0  3  train  foo

In [14]:
df.head()

                   A         B         C         D
2026-01-02 -0.929508  0.794743  1.079821  1.115524
2026-01-03 -1.407306 -2.013805  0.329798  1.727386
2026-01-04 -1.148989  1.152806  0.369733 -0.013631
2026-01-05 -0.090984  0.617422  0.620825 -0.872470
2026-01-06  1.407513  0.521418 -1.991583  0.404384

In [15]:
df.tail(3)

                   A         B         C         D
2026-01-05 -0.090984  0.617422  0.620825 -0.872470
2026-01-06  1.407513  0.521418 -1.991583  0.404384
2026-01-07 -0.540120  0.276446  0.065943 -0.536695